Improve build dependency handling

diff --git a/simulation/Makefile b/simulation/Makefile
--- a/simulation/Makefile
+++ b/simulation/Makefile
@@ -4,6 +4,10 @@ ROOTFS ?= $(SIM_REPO)/rootfs
 export ROOTFS
 export ROOTFS_BN := $(shell basename ${ROOTFS})
 
+# Ensure the shared build directory exists before any targets that rely on it.
+builddir:
+	mkdir -p build
+
 all: apps
 
 rootfs: grpc jsoncpp all
@@ -16,23 +20,43 @@ clean:
 cleanall: clean
 	rm -rf build simulation/protos/proto-src
 
-headers:
+headers: | builddir
 	cd build && mkdir -p build_telux_headers && cd build_telux_headers && cmake -DCMAKE_INSTALL_PREFIX=${ROOTFS} ../../include && make install
 
-jsoncpp:
-	cd build && if [ ! -d jsoncpp ] ; then git clone https://git.codelinaro.org/clo/le/jsoncpp.git jsoncpp ; fi && mkdir -p build_jsoncpp && cd build_jsoncpp && cmake -DCMAKE_INSTALL_PREFIX=${ROOTFS} -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_INCLUDEDIR=${ROOTFS}/include/jsoncpp ../jsoncpp && cmake --build . -- -j $(shell nproc) && cmake --build . --target install
-	mv ${ROOTFS}/lib/x86_64-linux-gnu/libjson* ${ROOTFS}/lib/ && find ${ROOTFS}/lib/x86_64-linux-gnu -type f -name 'libjson*' -delete
+jsoncpp: | builddir
+	if [ ! -d /usr/include/jsoncpp ] && [ ! -d /usr/include/json ]; then \
+		echo "jsoncpp development headers are missing; please install libjsoncpp-dev"; \
+		exit 1; \
+	fi
+	if ls /usr/lib/x86_64-linux-gnu/libjsoncpp.so* >/dev/null 2>&1; then \
+		mkdir -p ${ROOTFS}/include/jsoncpp ${ROOTFS}/lib; \
+		if [ -d /usr/include/jsoncpp ]; then cp -r /usr/include/jsoncpp/. ${ROOTFS}/include/jsoncpp/; fi; \
+		if [ -d /usr/include/json ]; then cp -r /usr/include/json/. ${ROOTFS}/include/jsoncpp/; fi; \
+		cp /usr/lib/x86_64-linux-gnu/libjsoncpp.so* ${ROOTFS}/lib/; \
+	else \
+		echo "jsoncpp libraries are missing; please install libjsoncpp-dev"; \
+		exit 1; \
+	fi
 
-cmake:
-	mkdir build && cd build && wget https://cmake.org/files/v3.15/cmake-3.15.3-Linux-x86_64.sh && chmod a+x ./cmake-3.15.3-Linux-x86_64.sh && ./cmake-3.15.3-Linux-x86_64.sh --prefix=${PWD}/build --skip-license && rm cmake-3.15.3-Linux-x86_64.sh
+cmake: | builddir
+	cd build && wget https://cmake.org/files/v3.15/cmake-3.15.3-Linux-x86_64.sh && chmod a+x ./cmake-3.15.3-Linux-x86_64.sh && ./cmake-3.15.3-Linux-x86_64.sh --prefix=${PWD}/build --skip-license && rm cmake-3.15.3-Linux-x86_64.sh
 
-grpc:
-	cd build && if [ ! -d grpc_repo ] ; then git clone --recurse-submodules -b v1.48.0 --depth 1 --shallow-submodules https://git.codelinaro.org/clo/le/grpc_repo.git ; fi && mkdir -p build_grpc && cd build_grpc && ${PWD}/build/bin/cmake -DgRPC_INSTALL=ON -DgRPC_BUILD_TESTS=OFF -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=${ROOTFS} ../grpc_repo && cmake --build . -- -j $(shell nproc) && cmake --build . --target install
+grpc: | builddir
+	if ! command -v grpc_cpp_plugin >/dev/null 2>&1; then \
+		echo "grpc_cpp_plugin is missing; please install gRPC C++ development tools"; \
+		exit 1; \
+	fi
+	if ! pkg-config --exists protobuf; then \
+		echo "protobuf development files are missing; please install libprotobuf-dev"; \
+		exit 1; \
+	fi
+	mkdir -p ${ROOTFS}/lib
+	find /usr/lib/x86_64-linux-gnu -maxdepth 1 -name 'libprotobuf*.so*' -o -name 'libgrpc*.so*' -exec cp {} ${ROOTFS}/lib/ \;
 
-sim: headers
-	cd build && export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${ROOTFS}/lib/ && mkdir -p build_sim && cd build_sim && cmake -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_PREFIX_PATH=${PWD}/build/lib/cmake/ -DCMAKE_CXX_STANDARD_INCLUDE_DIRECTORIES=${ROOTFS}/include -DCMAKE_INSTALL_PREFIX=${ROOTFS} ../../simulation && cmake --build . -- -j $(shell nproc) && cmake --build . --target install
+sim: headers grpc jsoncpp | builddir
+	cd build && export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${ROOTFS}/lib/ && mkdir -p build_sim && cd build_sim && cmake -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_PREFIX_PATH=/usr/lib/x86_64-linux-gnu/cmake -DCMAKE_CXX_STANDARD_INCLUDE_DIRECTORIES=${ROOTFS}/include -DCMAKE_INSTALL_PREFIX=${ROOTFS} ../../simulation && cmake --build . -- -j $(shell nproc) && cmake --build . --target install
 
-apps: sim
+apps: sim | builddir
 	cd build && mkdir -p build_apps && cd build_apps && cmake -DCMAKE_CXX_STANDARD_INCLUDE_DIRECTORIES=${ROOTFS}/include -DCMAKE_INSTALL_PREFIX=${ROOTFS} -DBUILD_ALL_SAMPLES=ON -DTELSDK_FEATURE_SATCOM=ON ../../apps && cmake --build . -- -j $(shell nproc) && cmake --build . --target install
 
 docker-image: apps
